### PR TITLE
Move to src/-package layout.

### PR DESCRIPTION
**Pull request by anntzer**
This has been discussed to death in certain circles (e.g. https://github.com/pypa/python-packaging-user-guide/issues/320) but in my personal view, there is one single clear advantage to using the src/-layout: when I develop packages, I tend to `pip install --editable` them (so that I don't need to reinstall them after each edit); but that works by adding their parent directory to sys.path.  Thus, in a non-src layout, `test_defopt` and (even worse) `setup` become importable packages, which pollute the global module namespace.

### CODE REVIEW

**Comment by evanunderscore** [comment]
To make sure I'm understanding you correctly - your workflow is to `pip install --editable` projects you work on into your global site-packages, which in this case leaves `test_defopt` and `setup` in your global namespace when you're doing unrelated things? Do you do this deliberately to use your in-development copy of `defopt` outside of when you're working on it?

I generally prefer the simplicity of a src-less layout, and try to avoid moving files where possible because it makes the history harder to navigate past that point in time. Having said that I'm not necessarily opposed to changing it if the benefits outweigh the downsides.

**Comment by anntzer** [comment]
> To make sure I'm understanding you correctly - your workflow is to pip install --editable projects you work on into your global site-packages, which in this case leaves test_defopt and setup in your global namespace when you're doing unrelated things?

Yes (More specifically, I do `pip install --user` -- I tend not to use venvs unless I really need the isolation, but just dump everything in the --user install.  The reason is that I depend on quite a few "large" libs (numpy, matplotlib, pyqt) and it's a bit silly to eat up hundreds of megabytes to install separate copies of them).

> Do you do this deliberately to use your in-development copy of defopt outside of when you're working on it?

Yes.

For example, right now this allows me to use code with https://github.com/evanunderscore/defopt/pull/60 in other scripts (as I have that branch checked out in my repo).

Admittedly, on simple, pure Python packages such as defopt, it would not be too much of an issue to just redo `pip install .` (non-editable) (although that'd need to be repeated in each venv -- but again it's compounded by the fact that I mostly have everything in my --user install).  However I also (for example) depend on matplotlib master for certain scripts and it'd be a bit of a pain to re-ôîp-install (and thus rebuild) matplotlib everytime I work on it.

So overall it's a small plus for me, but it's not the end of the world if you really don't like the src-layout and reject the changes either.

**Comment by anntzer** [comment]
Let's just close this if that's not going to happen.

**Comment by anntzer** [comment]
The package is small enough that I'll try just using non-editable installs for my workflow for now (per the above).

**Pull request closed without merging**
