### PR TITLE
Fix problem with private arg w/ default

### PR DESCRIPTION
**Pull request by elgow**
see issue https://github.com/evanunderscore/defopt/issues/50

### CODE REVIEW

**Comment by anntzer** [comment]
I think the correct fix is to not fetch private arguments in _call_function.  If a private argumenthas no default, we necessarily just error out.

e.g.
```
diff --git a/defopt.py b/defopt.py
index 7ed73b0..d1f2c8d 100644
--- a/defopt.py
+++ b/defopt.py
@@ -164,11 +164,15 @@ class _NoTypeFormatter(_Formatter):
     show_types = False
 
 
-def _populate_parser(func, parser, parsers, short, strict_kwonly):
+def _public_signature(func):
     full_sig = _inspect_signature(func)
-    sig = full_sig.replace(
+    return full_sig.replace(
         parameters=list(param for param in full_sig.parameters.values()
                         if not param.name.startswith('_')))
+
+
+def _populate_parser(func, parser, parsers, short, strict_kwonly):
+    sig = _public_signature(func)
     doc = _parse_function_docstring(func)
     hints = _get_type_hints(func)
     parser.description = doc.text
@@ -347,7 +351,7 @@ def _get_union_args(union):
 def _call_function(func, args):
     positionals = []
     keywords = {}
-    sig = _inspect_signature(func)
+    sig = _public_signature(func)
     for name, param in sig.parameters.items():
         arg = getattr(args, name)
         if param.kind in [param.POSITIONAL_ONLY, param.POSITIONAL_OR_KEYWORD]:
```

**Comment by elgow** [comment]
That sounds like a better solution that has the advantage of fail-fast behavior. As long as the case that I hit which prevents using private args at all is covered then I could live with either. 

Thanks for your fast and friendly response,

   Ed

**Comment by evanunderscore** [comment]
I agree with @anntzer's assessment. We already have logic to exclude the argument from the parser but it looks like we forgot to test actually calling the function.

@elgow If you'd like to update the merge request, plus add a test that verifies the problem is fixed, we can merge this in.

**Comment by evanunderscore** [comment]
Fixed by #53. Thanks all for your work.

**Pull request closed without merging**
